[2025-05-30T14:37:59.697+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-05-30T14:37:59.709+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: companies_house_pipeline.create_company_table manual__2025-05-30T14:37:58.272219+00:00 [queued]>
[2025-05-30T14:37:59.713+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: companies_house_pipeline.create_company_table manual__2025-05-30T14:37:58.272219+00:00 [queued]>
[2025-05-30T14:37:59.713+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2025-05-30T14:37:59.721+0000] {taskinstance.py:2888} INFO - Executing <Task(PostgresOperator): create_company_table> on 2025-05-30 14:37:58.272219+00:00
[2025-05-30T14:37:59.723+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=31) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-30T14:37:59.724+0000] {standard_task_runner.py:72} INFO - Started process 32 to run task
[2025-05-30T14:37:59.725+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'companies_house_pipeline', 'create_company_table', 'manual__2025-05-30T14:37:58.272219+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/companies_house_pipeline.py', '--cfg-path', '/tmp/tmpcr6vaqo1']
[2025-05-30T14:37:59.726+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask create_company_table
[2025-05-30T14:37:59.755+0000] {task_command.py:467} INFO - Running <TaskInstance: companies_house_pipeline.create_company_table manual__2025-05-30T14:37:58.272219+00:00 [running]> on host 493320a4ac14
[2025-05-30T14:37:59.800+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='companies_house_pipeline' AIRFLOW_CTX_TASK_ID='create_company_table' AIRFLOW_CTX_EXECUTION_DATE='2025-05-30T14:37:58.272219+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-30T14:37:58.272219+00:00'
[2025-05-30T14:37:59.800+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-05-30T14:37:59.808+0000] {sql.py:306} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS company (
        company_number VARCHAR(20) PRIMARY KEY,
        company_name TEXT,
        company_status TEXT,
        incorporation_date DATE
    );
    
[2025-05-30T14:37:59.815+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-05-30T14:37:59.822+0000] {base.py:84} INFO - Retrieving connection 'postgres_default'
[2025-05-30T14:37:59.825+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 312, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 767, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 874, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-05-30T14:37:59.834+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=companies_house_pipeline, task_id=create_company_table, run_id=manual__2025-05-30T14:37:58.272219+00:00, execution_date=20250530T143758, start_date=20250530T143759, end_date=20250530T143759
[2025-05-30T14:37:59.843+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-05-30T14:37:59.844+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 5 for task create_company_table (connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"
; 32)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 312, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 767, in run
    with self._create_autocommit_connection(autocommit) as conn:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 874, in _create_autocommit_connection
    with closing(self.get_conn()) as conn:
                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 181, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "postgres" (172.18.0.2), port 5432 failed: FATAL:  password authentication failed for user "postgres"

[2025-05-30T14:37:59.867+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-05-30T14:37:59.875+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class SimpleHttpOperator. (Class `SimpleHttpOperator` is deprecated and will be removed in a future release. Please use `HttpOperator` instead.)
  result = cls.__new__(cls)

[2025-05-30T14:37:59.875+0000] {warnings.py:112} WARNING - /usr/local/lib/python3.12/site-packages/***/models/baseoperator.py:1378: AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `***.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
  result = cls.__new__(cls)

[2025-05-30T14:37:59.882+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-30T14:37:59.883+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
